test {
    common {
        id: "b_frames"
        description: "B-Frame Testing"
    }
    configure {
        codec: "encoder.avc"
        bitrate: "1000 kbps"
        bitrate_mode: vbr
        i_frame_interval: 2000
        parameter {
            key: "max-bframes"
            type: intType
            value: "1"
        }
    }
}
