test {
    common {
        id: "bframes"
        description: "Verify B-Frames Encoding"
    }
    configure {
        bitrate_mode: vbr
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
        parameter {
            key: "max-bframes"
            type: intType
            value: "1"
        }
        parameter {
            key: "ts-schema"
            type: stringType
            value: "android.generic.1+2"
        }
    }
}
