test {
    common {
        id: "decoder_buffer"
        description: "Verify decoder - buffer"
    }
    configure {
        codec: "OMX.google.h264.decoder"
        encode: false
        bitrate: "100 kbps"
    }
}
