test {
    common {
        id: "bitrate_surface_rgba"
        description: "Verify encoding bitrate - surface - rgba"
    }
    input {
        filepath: "/tmp/akiyo_qcif.rgba"
        resolution: "176x144"
        pix_fmt: rgba
        framerate: 30
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
        surface: true
    }
}
