test {
    common {
        id: "bitrate_buffer"
        description: "Verify encoding bitrate - buffer"
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
    }
}
