test {
    common {
        id: "bitrate_transcoder_show"
        description: "Verify encoding bitrate - surface"
    }
    input {
        show: true
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
        surface: true
    }
}
