test {
    common {
        id: "bitrate_surface"
        description: "Verify encoding bitrate - surface"
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
        surface: true
    }
}
