test {
    common {
        id: "bitrate_surface"
        description: "Verify encoding bitrate - surface"
    }
    input {
        filepath: "/tmp/akiyo_qcif.yuv"
        resolution: "176x144"
        framerate: 30
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
        surface: true
    }
}
