test {
    input {
        filepath: "/tmp/akiyo_qcif.mp4"
        device_decode: true
    }
    common {
        id: "decoder_buffer"
        description: "Verify decoder - buffer"
    }
    configure {
        encode: false
    }
}
