test {
    common {
        id: "Camera"
        description: "Camera source encoding"
    }
    input {
        filepath: "camera"
        resolution: "1280x720"
        framerate: 30
        playout_frames: 300
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
        surface: true
    }
}
