test {
    common {
        id: "camera_parallel"
        description: "Camera source encoding"
    }
    input {
        filepath: "camera"
        resolution: "1280x720"
        framerate: 30
        playout_frames: 300
        show: true
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "1000 kbps"
        surface: true
    }
    parallel {
        test {
            common {
                id: "camera_parallel"
                description: "Camera source encoding"
            }
            input {
                filepath: "camera"
                resolution: "1280x720"
                framerate: 30
                playout_frames: 300
            }
            configure {
                codec: "OMX.google.h264.encoder"
                bitrate: "1000 kbps"
                surface: true
            }
        }
    }
}
