test {
    common {
        id: "dynamic_bitrate"
        description: "Verify encoding bitrate"
    }
    input {
        playout_frames: 360
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "1Mbps"
    }
    runtime {
        video_bitrate {
            framenum: 60
            bitrate: "50k"
        }
        video_bitrate {
            framenum: 120
            bitrate: "100k"
        }
        video_bitrate {
            framenum: 180
            bitrate: "400k"
        }
    }
}
