test {
    common {
        id: "dynamic_idr"
        description: "Verify encoding bitrate on dynamic sync frame"
    }
    input {
        playout_frames: 180
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "400 kbps"
        i_frame_interval: 2000
    }
    runtime {
        request_sync: 30
        request_sync: 60
        request_sync: 90
        request_sync: 120
    }
}
