test {
    input {
        filepath: "/tmp/akiyo_qcif.y4m"
    }
    common {
        id: "lcevc_x264"
        description: "V-Nova's LCEVC x264 encoding"
    }
    configure {
        codec: "lcevc_h264"
        bitrate: "500 kbps"
        framerate: 30
        i_frame_interval: 10
        parameter {
            key: "base_encoder"
            type: stringType
            value: "x264"
        }
    }
}
