test {
    input {
        filepath: "/tmp/akiyo_qcif.y4m"
    }
    common {
        id: "qcom.ltr-2ref"
        description: "[QCOM] Dynamic LTR (Long-Term Reference) - 2 Frame Refs Test"
    }
    input {
        playout_frames: 900
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "100 kbps"
        bitrate_mode: cbr
        i_frame_interval: 2000
        parameter {
            key: "vendor.qti-ext-enc-ltr-count.num-ltr-frames"
            type: intType
            value: "2"
        }
        parameter {
            key: "vendor.qti-ext-enc-caps-ltr.max-frames"
            type: intType
            value: "2"
        }
    }
    runtime {
        parameter {
            framenum: 60
            key: "vendor.qti-ext-enc-ltr.mark-frame"
            type: intType,
            value: "1"
        }
        parameter {
            framenum: 400
            key: "vendor.qti-ext-enc-ltr.use-frame"
            type: intType,
            value: "0"
        }
        parameter {
            framenum: 500
            key: "vendor.qti-ext-enc-ltr.use-frame"
            type: intType,
            value: "1"
        }
        request_sync: 600
        parameter {
            framenum: 700
            key: "vendor.qti-ext-enc-ltr.use-frame"
            type: intType,
            value: "1"
        }
        parameter {
            framenum: 800
            key: "vendor.qti-ext-enc-ltr.use-frame"
            type: intType,
            value: "0"
        }
    }
}
