test {
    input {
        filepath: "/tmp/akiyo_qcif.mp4"
        device_decode: true
    }
    common {
        id: "bitrate_transcoder_surface"
        description: "Verify encoding bitrate - transcode usng surface"
    }
    configure {
        codec: "OMX.google.h264.encoder"
        bitrate: "200 kbps"
        surface: true
    }
}
